import Head from 'next/head'
import { Carousel } from 'antd';

import Owner from '../components/Owner';
import Hospital from '../components/Hospital';
import Verifier from '../components/Verifiers';
import Dapp from '../components/Dapp';
import { LeftOutlined, RightOutlined } from '@ant-design/icons';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Carousel 
          arrows
          prevArrow={<LeftOutlined />}
          nextArrow={<RightOutlined />}
          style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', margin: 0, padding: 0}}
        >
          <Owner />
          <Hospital />
          <Dapp />
          <Verifier />
        </Carousel>
      </main>
    </>
  )
}
